### ISSUE TITLE
Extracting 3D information

### ISSUE THREAD

**Issue by debortoli** [romulogcerqueira/sonar_simulation-buildconf#29]
Hi @romulogcerqueira,

Thank you for your continued development on this simulator, its very useful! I am currently working on a model that maps 2D sonar image pixels into 3D (range, bearing, elevation angle or X,Y,Z in camera frame). 

I am wondering if your simulator has an easy way to compute this information for a given sonar frame. It seems like this information would be used in normal_depth_map to compute the depth map, but I'm getting lost trying to determine where exactly the 3D information is. Thanks!

**Comment by romulogcerqueira** [comment]
Hi @debortoli,

it is not possible to determine the elevation angle from a single 2D sonar frame.

In order to acquire the 3D data, you must use an external device to fuse with sonar data (e.g. DVL provides the distance to the ground) or capture multiple frames from the same target to compute an "acoustic odometry" (similar to image-based 3D reconstruction techniques).

**Comment by debortoli** [comment]
Hi @romulogcerqueira ,

Thanks for the response! I just wanted to clarify: I am only wondering about extracting the 3D information from your simulator. So for the process in the image below, I would guess that 3D information for each pixel would be available in the simulator, but I was wondering how to access it. Thanks!
![Screenshot from 2021-04-19 09-09-54](https://user-images.githubusercontent.com/6937030/115268712-6827d180-a0ef-11eb-8afa-cdd2bc3dcdca.png)
